services:
  api:
    image: ultimate-blog-api:dev
    build:
      context: .
      dockerfile: ./api/Dockerfile
      target: dev
    volumes:
      - ./api:/app
      - /app/node_modules

  client:
    image: ultimate-blog-client:dev
    build:
      context: .
      dockerfile: ./client/Dockerfile
      target: dev
    volumes:
      - ./client:/app
      - /app/node_modules

  nginx:
    volumes:
      - ./nginx/dev.conf:/etc/nginx/nginx.conf
