services:
  api:
    image: ultimate-blog-api:prod
    build:
      context: .
      dockerfile: ./api/Dockerfile

  client:
    image: ultimate-blog-client:prod
    build:
      context: .
      dockerfile: ./client/Dockerfile
      target: prod

  nginx:
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx/prod.conf:/etc/nginx/nginx.conf
      - /var/www/acme-challenge:/var/www/acme-challenge
