services:
  api:
    depends_on:
      - mongo
    volumes:
      - storage:/data

  client:
    environment:
      API_CONTAINER_URL: http://api:3001/api
    depends_on:
      - api

  mongo:
    image: mongo
    volumes:
      - db-data:/data/db

  nginx:
    image: nginx:1.25.1-alpine
    volumes:
      - storage:/data
    ports:
      - "3000:80"
    depends_on:
      - api
      - client

volumes:
  db-data:
  storage:
